<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-08-31 13:34
=======
# Generated by Django 4.1 on 2022-08-31 05:55
>>>>>>> bc0aa42eb524c864ff3798b3593e67eeba68c8d0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('countries', '0001_initial'),
=======
        ('countries', '0003_remove_country_id_alter_country_code'),
>>>>>>> bc0aa42eb524c864ff3798b3593e67eeba68c8d0
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
        ),
    ]
