# Generated by Django 4.0.5 on 2022-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
