# Generated by Django 4.1 on 2022-09-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessPoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
