<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-08-31 13:34

from django.db import migrations, models
=======
# Generated by Django 4.1 on 2022-08-31 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> bc0aa42eb524c864ff3798b3593e67eeba68c8d0


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessPoints', '0001_initial'),
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> bc0aa42eb524c864ff3798b3593e67eeba68c8d0
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('access_point', models.ManyToManyField(to='accessPoints.accesspoint')),
<<<<<<< HEAD
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> bc0aa42eb524c864ff3798b3593e67eeba68c8d0
            ],
        ),
    ]
