# Generated by Django 4.1 on 2022-09-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
    ]
